Use timezone aware date time consistently
datetime.now() returns naive datetime objects, without timezone. That
caused the test suite to fail around midnight with:

```
____________________________ test_collect_dsp_stats ____________________________
[gw2] linux -- Python 3.13.9 /home/runner/work/la-communaute/la-communaute/.venv/bin/python

db = None

    def test_collect_dsp_stats(db):
        # no stat collected
        assert collect_dsp_stats() == (date(2024, 1, 1), 0)

        # one stat to collected for one dsp
        DSPFactory(months_ago=3)
        assert collect_dsp_stats() == (date(2024, 1, 1), 1)
        stat = Stat.objects.get()
        assert stat.name == "dsp"
        assert stat.period == "day"
        assert stat.value == 1
>       assert stat.date == datetime.now().date() - relativedelta(months=3)
E       assert datetime.date(2025, 9, 2) == (datetime.date(2025, 12, 1) - relativedelta(months=+3))
E        +  where datetime.date(2025, 9, 2) = <Stat: dsp - 2025-09-02 - day>.date
E        +  and   datetime.date(2025, 12, 1) = <built-in method date of datetime.datetime object at 0x7f86aa99f240>()
E        +    where <built-in method date of datetime.datetime object at 0x7f86aa99f240> = datetime.datetime(2025, 12, 1, 23, 56, 21, 610721).date
E        +      where datetime.datetime(2025, 12, 1, 23, 56, 21, 610721) = <built-in method now of type object at 0x14b15e8>()
E        +        where <built-in method now of type object at 0x14b15e8> = datetime.now
E        +  and   relativedelta(months=+3) = relativedelta(months=3)

lacommunaute/surveys/tests/test_stats.py:21: AssertionError
=========================== short test summary info ============================
FAILED lacommunaute/surveys/tests/test_stats.py::test_collect_dsp_stats - assert datetime.date(2025, 9, 2) == (datetime.date(2025, 12, 1) - relativedelta(months=+3))
 +  where datetime.date(2025, 9, 2) = <Stat: dsp - 2025-09-02 - day>.date
 +  and   datetime.date(2025, 12, 1) = <built-in method date of datetime.datetime object at 0x7f86aa99f240>()
 +    where <built-in method date of datetime.datetime object at 0x7f86aa99f240> = datetime.datetime(2025, 12, 1, 23, 56, 21, 610721).date
 +      where datetime.datetime(2025, 12, 1, 23, 56, 21, 610721) = <built-in method now of type object at 0x14b15e8>()
 +        where <built-in method now of type object at 0x14b15e8> = datetime.now
 +  and   relativedelta(months=+3) = relativedelta(months=3)
====== 1 failed, 676 passed, 2 skipped, 599 warnings in 62.59s (0:01:02) =======
Error: Process completed with exit code 1.
```